<a href="https://colab.research.google.com/github/SnehaSanjana/Machine-Learning-/blob/main/parkinson_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.metrics import accuracy_score

In [ ]:
parkinsons_data = pd.read_csv('/content/pd_speech_features (1).csv')
parkinsons_data

,id,gender,PPE,DFA,RPDE,numPulses,numPeriodsPulses,meanPeriodPulses,stdDevPeriodPulses,locPctJitter,...,tqwt_kurtosisValue_dec_28,tqwt_kurtosisValue_dec_29,tqwt_kurtosisValue_dec_30,tqwt_kurtosisValue_dec_31,tqwt_kurtosisValue_dec_32,tqwt_kurtosisValue_dec_33,tqwt_kurtosisValue_dec_34,tqwt_kurtosisValue_dec_35,tqwt_kurtosisValue_dec_36,class
0,0,1,0.85247,0.71826,0.57227,240,239,0.008064,0.000087,0.00218,...,1.5620,2.6445,3.8686,4.2105,5.1221,4.4625,2.6202,3.0004,18.9405,1
1,0,1,0.76686,0.69481,0.53966,234,233,0.008258,0.000073,0.00195,...,1.5589,3.6107,23.5155,14.1962,11.0261,9.5082,6.5245,6.3431,45.1780,1
2,0,1,0.85083,0.67604,0.58982,232,231,0.008340,0.000060,0.00176,...,1.5643,2.3308,9.4959,10.7458,11.0177,4.8066,2.9199,3.1495,4.7666,1
3,1,0,0.41121,0.79672,0.59257,178,177,0.010858,0.000183,0.00419,...,3.7805,3.5664,5.2558,14.0403,4.2235,4.6857,4.8460,6.2650,4.0603,1
4,1,0,0.32790,0.79782,0.53028,236,235,0.008162,0.002669,0.00535,...,6.1727,5.8416,6.0805,5.7621,7.7817,11.6891,8.2103,5.0559,6.1164,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,250,0,0.80903,0.56355,0.28385,417,416,0.004627,0.000052,0.00064,...,3.0706,3.0190,3.1212,2.4921,3.5844,3.5400,3.3805,3.2003,6.8671,0
752,250,0,0.16084,0.56499,0.59194,415,413,0.004550,0.000220,0.00143,...,1.9704,1.7451,1.8277,2.4976,5.2981,4.2616,6.3042,10.9058,28.4170,0
753,251,0,0.88389,0.72335,0.46815,381,380,0.005069,0.000103,0.00076,...,51.5607,44.4641,26.1586,6.3076,2.8601,2.5361,3.5377,3.3545,5.0424,0
754,251,0,0.83782,0.74890,0.49823,340,339,0.005679,0.000055,0.00092,...,19.1607,12.8312,8.9434,2.2044,1.9496,1.9664,2.6801,2.8332,3.7131,0
755,251,0,0.81304,0.76471,0.46374,340,339,0.005676,0.000037,0.00078,...,62.9927,21.8152,9.2457,4.8555,3.0551,3.0415,4.0116,2.6217,3.1527,0

In [ ]:
parkinsons_data.head()

,id,gender,PPE,DFA,RPDE,numPulses,numPeriodsPulses,meanPeriodPulses,stdDevPeriodPulses,locPctJitter,...,tqwt_kurtosisValue_dec_28,tqwt_kurtosisValue_dec_29,tqwt_kurtosisValue_dec_30,tqwt_kurtosisValue_dec_31,tqwt_kurtosisValue_dec_32,tqwt_kurtosisValue_dec_33,tqwt_kurtosisValue_dec_34,tqwt_kurtosisValue_dec_35,tqwt_kurtosisValue_dec_36,class
0,0,1,0.85247,0.71826,0.57227,240,239,0.008064,0.000087,0.00218,...,1.5620,2.6445,3.8686,4.2105,5.1221,4.4625,2.6202,3.0004,18.9405,1
1,0,1,0.76686,0.69481,0.53966,234,233,0.008258,0.000073,0.00195,...,1.5589,3.6107,23.5155,14.1962,11.0261,9.5082,6.5245,6.3431,45.1780,1
2,0,1,0.85083,0.67604,0.58982,232,231,0.008340,0.000060,0.00176,...,1.5643,2.3308,9.4959,10.7458,11.0177,4.8066,2.9199,3.1495,4.7666,1
3,1,0,0.41121,0.79672,0.59257,178,177,0.010858,0.000183,0.00419,...,3.7805,3.5664,5.2558,14.0403,4.2235,4.6857,4.8460,6.2650,4.0603,1
4,1,0,0.32790,0.79782,0.53028,236,235,0.008162,0.002669,0.00535,...,6.1727,5.8416,6.0805,5.7621,7.7817,11.6891,8.2103,5.0559,6.1164,1

In [ ]:
parkinsons_data.shape

(756, 755)

In [ ]:
parkinsons_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Columns: 755 entries, id to class
dtypes: float64(749), int64(6)
memory usage: 4.4 MB

In [ ]:
parkinsons_data.isnull().sum()

id                           0
gender                       0
PPE                          0
DFA                          0
RPDE                         0
                            ..
tqwt_kurtosisValue_dec_33    0
tqwt_kurtosisValue_dec_34    0
tqwt_kurtosisValue_dec_35    0
tqwt_kurtosisValue_dec_36    0
class                        0
Length: 755, dtype: int64

In [ ]:
parkinsons_data.describe()

,id,gender,PPE,DFA,RPDE,numPulses,numPeriodsPulses,meanPeriodPulses,stdDevPeriodPulses,locPctJitter,...,tqwt_kurtosisValue_dec_28,tqwt_kurtosisValue_dec_29,tqwt_kurtosisValue_dec_30,tqwt_kurtosisValue_dec_31,tqwt_kurtosisValue_dec_32,tqwt_kurtosisValue_dec_33,tqwt_kurtosisValue_dec_34,tqwt_kurtosisValue_dec_35,tqwt_kurtosisValue_dec_36,class
count,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000,...,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000
mean,125.500000,0.515873,0.746284,0.700414,0.489058,323.972222,322.678571,0.006360,0.000383,0.002324,...,26.237251,22.840337,18.587888,13.872018,12.218953,12.375335,14.799230,14.751559,31.481110,0.746032
std,72.793721,0.500079,0.169294,0.069718,0.137442,99.219059,99.402499,0.001826,0.000728,0.002628,...,42.220693,32.626464,25.537464,20.046029,17.783642,16.341665,15.722502,14.432979,34.230991,0.435568
min,0.000000,0.000000,0.041551,0.543500,0.154300,2.000000,1.000000,0.002107,0.000011,0.000210,...,1.509800,1.531700,1.582900,1.747200,1.789500,1.628700,1.861700,1.955900,2.364000,0.000000
25%,62.750000,0.000000,0.762833,0.647053,0.386537,251.000000,250.000000,0.005003,0.000049,0.000970,...,2.408675,3.452800,3.354825,3.077450,2.937025,3.114375,3.665925,3.741275,3.948750,0.000000
50%,125.500000,1.000000,0.809655,0.700525,0.484355,317.000000,316.000000,0.006048,0.000077,0.001495,...,5.586300,7.062750,6.077400,4.770850,4.300450,4.741450,6.725700,7.334250,10.637250,1.000000
75%,188.250000,1.000000,0.834315,0.754985,0.586515,384.250000,383.250000,0.007528,0.000171,0.002520,...,28.958075,29.830850,21.944050,13.188000,10.876150,12.201325,21.922050,22.495175,61.125325,1.000000
max,251.000000,1.000000,0.907660,0.852640,0.871230,907.000000,905.000000,0.012966,0.003483,0.027750,...,239.788800,203.311300,121.542900,102.207000,85.571700,73.532200,62.007300,57.544300,156.423700,1.000000

In [ ]:
parkinsons_data['class'].value_counts()

1    564
0    192
Name: class, dtype: int64

In [ ]:
parkinsons_data.groupby('class').mean()

,id,gender,PPE,DFA,RPDE,numPulses,numPeriodsPulses,meanPeriodPulses,stdDevPeriodPulses,locPctJitter,...,tqwt_kurtosisValue_dec_27,tqwt_kurtosisValue_dec_28,tqwt_kurtosisValue_dec_29,tqwt_kurtosisValue_dec_30,tqwt_kurtosisValue_dec_31,tqwt_kurtosisValue_dec_32,tqwt_kurtosisValue_dec_33,tqwt_kurtosisValue_dec_34,tqwt_kurtosisValue_dec_35,tqwt_kurtosisValue_dec_36
class,,,,,,,,,,,,,,,,,,,,,
0,139.421875,0.359375,0.767434,0.663866,0.430807,372.244792,371.031250,0.005699,0.000290,0.001405,...,47.053772,45.754404,32.006881,21.592319,14.797452,10.726868,9.021939,9.619535,9.326543,15.074830
1,120.760638,0.569149,0.739084,0.712856,0.508888,307.539007,306.218085,0.006585,0.000414,0.002637,...,12.165554,19.593113,19.719812,17.565102,13.556976,12.726897,13.516916,16.562531,16.598373,37.066227

In [ ]:
X = parkinsons_data.drop(columns=['id','class'], axis=1)
Y = parkinsons_data['class']

In [ ]:
print(Y)

0      1
1      1
2      1
3      1
4      1
      ..
751    0
752    0
753    0
754    0
755    0
Name: class, Length: 756, dtype: int64

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(756, 753) (604, 753) (152, 753)

In [ ]:
scaler = StandardScaler()

In [ ]:
scaler.fit(X_train)

StandardScaler()

In [ ]:
X_train = scaler.transform(X_train)

X_test = scaler.transform(X_test)

In [ ]:
print(X_train)

[[ 0.99669421  0.3484459   1.94836243 ... -0.24665913  0.08898025
   1.31564894]
 [-1.00331676  0.59741695 -0.07079278 ... -0.52487784 -0.30682153
   0.78639303]
 [-1.00331676 -2.04139106 -1.54292361 ...  1.17549419  0.06506809
  -0.70808211]
 ...
 [ 0.99669421  0.44900144  0.01789488 ...  0.542305    0.06847005
   0.80891976]
 [-1.00331676  0.60715013 -2.02276462 ...  2.16642074  2.15803582
   1.6908753 ]
 [ 0.99669421  0.23933508 -0.99856972 ...  1.11266044  1.20986453
   1.22173395]]

In [ ]:
model = svm.SVC(kernel='linear')

In [ ]:
model.fit(X_train, Y_train)

SVC(kernel='linear')

In [ ]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(Y_train, X_train_prediction)

In [ ]:
print('Accuracy score of training data : ', training_data_accuracy)

Accuracy score of training data :  1.0

In [ ]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(Y_test, X_test_prediction)

In [ ]:
print('Accuracy score of test data : ', test_data_accuracy)

Accuracy score of test data :  0.8157894736842105

In [ ]:
input_data = (0.83457,0.64883,0.61752,240,239,0.00807081,0.000126416,0.00393,3.17E-05,0.00078,0.00194,0.00233,0.11204,1.015,0.04562,0.07106,0.13472,0.13687,0.968542,0.032883,15.542,67.83775461,72.74947927,70.69666937,595.7864993,1155.34221,2499.672523,3535.469292,34.52592105,108.0343517,242.8160967,141.5599814,0.79398,15.0815,4.0806,0.81299,0.12496,0.14801,1432293.88,1.6725,3.0088,0.00054638,0.00028594,0.96059,151.5645,197.4335,1.2561,1.2597,55.7118,3.2105,18.6901,0.19917,8.0885,0.17417,9.3353,14.2819,6.546,0.70505,2.0768,-2.2319,-0.16168,-1.844,-0.91795,0.86749,0.99869,-1.1072,0.57457,0.30556,0.0012575,0.0061519,0.00078808,-0.0030558,-0.0013769,-0.00037857,-0.00020155,0.0021368,-0.00017873,0.00049621,0.00098839,-0.0046027,0.00036782,0.0015716,-0.00020553,-0.0012368,0.00012696,-0.0003419,0.00043963,-0.00079558,0.00088155,-0.00086275,0.00015216,-0.00040312,7.82E-05,-0.00014834,0.0007315,-7.70E-05,0.24255,0.72374,0.72605,0.677,0.64637,0.56532,0.60617,0.52494,0.35384,0.37432,0.32389,0.37946,0.28315,0.26392,0.039846,0.10612,0.095421,0.089045,0.073266,0.067838,0.082758,0.075409,0.045262,0.049971,0.046164,0.056769,0.047504,0.039201,0.015707,0.048123,0.051393,0.049276,0.038342,0.036951,0.040287,0.039275,0.023995,0.024561,0.024483,0.027272,0.024284,0.019498,99.9984,5.44E-07,5.98E-06,5.45E-05,6.09E-05,3.58E-05,0.00020107,8.96E-05,0.00071078,0.00019919,0.00021845,4.4794,6.8216,-288.6923,-337.8376,-221.9546,-2308.0553,-794.3347,-10640.534,-2394.9389,-2608.3988,-642.2966,-175.7464,-15.7933,26.0913,-2.8263,16.7209,8.1059,21.5625,16.8752,26.3782,0.010552,0.17397,3.6351,7.0125,5.5524,24.2871,10.5219,193.1233,29.7935,31.673,0.022389,0.34893,5.4683,7.9169,8.5458,49.9428,31.8585,318.7831,79.0443,82.6665,-34535853.22,-41852540.09,-55854055.4,-81648325.74,-133699848.5,-240730549,-476820457.3,-938403225.6,-1962222599,-4095284829,1116.605,673.2552,446.02,323.4034,262.7886,235.2519,232.5354,228.4263,238.8235,249.2208,601.5262,2118.352,6753.8004,19749.4743,51338.3394,120499.6595,255508.8988,542879.9327,1086039.268,2171916.303,4365.3003,11669.9845,29209.0627,69938.2375,158672.4082,342138.1298,691257.0358,1433970.303,2861202.662,5731017.103,99.9999,2.44E-08,2.59E-07,2.43E-06,2.68E-06,1.59E-06,8.91E-06,3.93E-06,3.14E-05,8.71E-06,9.54E-06,0.0011362,0.0094741,0.065364,0.071278,0.040728,0.15981,0.08588,0.40347,0.14991,0.16532,-1684.2768,-768.1811,-381.8042,-224.7854,-193.939,-147.1401,-146.2004,-123.3033,-127.9984,-118.8809,6.97E-07,1.10E-05,0.00023742,0.00045043,0.00035865,0.0015838,0.00067661,0.012441,0.0019041,0.0020235,1.52E-06,2.17E-05,0.0003624,0.00051359,0.00054986,0.0032587,0.0020464,0.020569,0.0050519,0.0052629,-19292.8244,-25759.5922,-37066.2237,-57558.197,-99093.8472,-186354.1803,-384210.3353,-783084.5573,-1690953.516,-3631476.121,414.7077,276.5767,198.6902,154.0111,132.3649,124.3139,128.0983,130.4949,140.8921,151.2893,0.86979,3.0768,9.8666,28.846,74.9979,176.3833,374.6586,798.6186,1597.3315,3194.6091,6.3539,16.868,42.4694,101.9557,231.0372,498.5419,1021.4182,2107.9128,4213.7695,8430.2892,0.00015583,0.00023555,0.00072865,0.0015181,0.0019159,0.0011547,0.00036911,0.00093715,0.0013627,0.0014164,0.0012539,0.00074574,0.0039918,0.012489,0.015667,0.03664,0.15054,0.30021,0.21048,0.085732,0.030559,0.012403,0.011786,0.0059648,0.0051594,0.03118,0.057463,0.017464,0.00021339,6.20E-05,7.21E-05,7.68E-05,3.22E-05,5.07E-06,2.62E-06,6.84E-06,1.5469,2.2328,6.065,11.4775,13.9366,8.7764,3.2889,7.483,10.2217,10.4858,9.2822,5.6221,24.9204,63.9886,71.9565,142.236,401.2127,596.7257,420.7836,226.2143,104.8664,49.4701,48.3861,26.7074,22.7623,87.9471,125.904,52.6574,1.3237,0.4373,0.49073,0.50124,0.22735,0.042653,0.022404,0.048908,-2017921.888,-1603797.351,-1244695.126,-947680.6105,-744005.3357,-622859.6918,-522754.0327,-399938.8812,-318929.4701,-258217.7024,-213582.8373,-184997.2424,-125966.1297,-90558.3161,-74186.2441,-52705.563,-33031.989,-22078.4987,-20655.9019,-19357.0833,-18200.0127,-17449.8106,-13186.4123,-12040.9117,-9957.1035,-5763.1214,-4007.7395,-4222.4336,-6860.2526,-6375.8017,-5167.0846,-4179.736,-3793.5745,-3573.7159,-3123.1126,-3866.9472,1.88E-06,2.40E-06,1.05E-05,2.97E-05,4.97E-05,3.69E-05,8.44E-06,3.75E-05,6.97E-05,8.47E-05,0.00010243,3.91E-05,0.00026896,0.0015824,0.0022517,0.0041863,0.026744,0.084911,0.068196,0.034096,0.01486,0.0055696,0.0086343,0.0047687,0.0016728,0.028263,0.0909,0.026177,0.00024636,0.00013948,0.00019478,0.00028284,0.00013271,2.22E-05,1.54E-05,2.28E-05,5.25E-06,6.09E-06,2.65E-05,7.88E-05,0.00012539,9.21E-05,1.66E-05,5.48E-05,0.00010912,0.00011943,0.00012216,9.30E-05,0.00029305,0.001593,0.003365,0.0065594,0.027006,0.074049,0.078467,0.035143,0.012492,0.006799,0.0039732,0.0028693,0.0019825,0.01717,0.044794,0.013977,0.00036536,0.00018076,0.00021608,0.00037401,0.00016056,3.51E-05,3.11E-05,0.00011189,-2.10E-07,-2.14E-07,-1.44E-07,6.12E-07,1.48E-06,3.78E-06,2.59E-06,-3.06E-05,-8.43E-06,-1.95E-05,-9.58E-06,3.05E-05,-0.00011478,-1.91E-05,0.00015713,5.92E-05,0.00045066,0.00025272,-0.0032241,-0.00027576,-0.00040221,-0.00052184,-0.002583,-0.0011377,2.26E-05,-0.0042065,-0.0012536,0.0042469,-0.00044646,-0.00027155,-9.35E-05,0.00030113,0.00015145,-9.51E-05,-2.62E-05,2.00E-07,-1.36E-21,1.30E-21,1.23E-21,9.94E-22,-6.21E-21,1.95E-21,-4.49E-21,7.82E-21,-1.65E-21,3.04E-22,-7.11E-20,-1.97E-20,1.02E-19,1.24E-19,9.54E-20,-1.27E-20,-6.42E-19,-1.03E-18,-6.49E-19,-1.92E-19,3.98E-19,8.04E-19,-8.63E-20,-3.63E-19,-2.72E-19,5.18E-19,5.94E-19,-1.20E-18,1.21E-21,-7.30E-20,7.69E-20,-1.14E-19,2.52E-20,9.10E-21,-8.02E-20,-0.00014649,0.0010453,0.0014079,0.0027126,0.004289,0.0052782,0.0044888,0.0027801,0.0048526,0.0064101,0.0071589,0.0073785,0.0062335,0.015798,0.030611,0.037558,0.062925,0.13972,0.21615,0.19823,0.13863,0.090646,0.06327,0.067566,0.052642,0.053636,0.14453,0.21481,0.12978,0.01571,0.0092887,0.010963,0.012412,0.0087971,0.0038308,0.0030207,0.0043566,-0.016095,-0.011777,-0.024769,-0.042056,-0.048171,-0.039358,-0.018122,-0.027298,-0.03737,-0.032664,-0.031909,-0.036994,-0.049355,-0.11444,-0.15852,-0.22142,-0.42949,-0.67712,-0.69224,-0.4052,-0.26313,-0.19184,-0.1476,-0.12773,-0.15482,-0.35218,-0.48941,-0.29304,-0.052821,-0.031006,-0.032626,-0.049424,-0.024723,-0.016003,-0.017492,-0.039055,0.024132,0.013049,0.023494,0.037086,0.051635,0.040946,0.020221,0.02667,0.039409,0.038772,0.039511,0.031022,0.051,0.11313,0.15243,0.24482,0.44753,0.63354,0.67596,0.43595,0.25709,0.18114,0.14909,0.12517,0.1442,0.35906,0.48471,0.30796,0.043649,0.034115,0.035414,0.048056,0.034399,0.018093,0.012633,0.033727,0.15101,0.029819,-0.0015634,0.0007992,-0.0084572,0.00019148,0.0012611,-0.01409,-0.042808,-0.012517,0.0093523,-0.044818,0.0069815,-0.0013338,-0.038749,0.037523,0.0061058,-0.00026316,-0.00080602,0.010686,-0.03072,0.014856,0.0028751,0.0064773,-0.0012461,-0.0043906,-0.00015771,0.0075285,-0.13163,0.089533,0.019003,0.0046091,-0.0039386,0.11892,-0.23833,-0.73095,14.5402,9.407,10.646,11.0284,10.6639,10.3428,4.7863,4.6168,4.8262,4.0516,3.585,5.0172,2.9564,3.1644,4.5034,3.5319,2.8242,2.6913,3.2608,3.02,2.6034,2.6766,1.8225,1.968,2.1768,1.9721,1.8574,1.8724,3.2987,3.5229,3.1712,3.9383,3.7813,5.1324,9.0292,35.2767,1)
# changing input data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the numpy array
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

# standardize the data
std_data = scaler.transform(input_data_reshaped)

prediction = model.predict(std_data)
print(prediction)


if (prediction[0] == 0):
  print("The Person does not have Parkinsons Disease")

else:
  print("The Person has Parkinsons")

[1]
The Person has Parkinsons

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"